apiVersion: v1
kind: Namespace
metadata:
  name: sample-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-controller
  namespace: sample-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sample-controller
rules:
  - verbs:
      - get
      - list
      - update
      - create
      - delete
      - watch
    resources:
      - deployments
    apiGroups:
      - apps
  - verbs:
      - get
      - list
      - update
      - create
      - delete
      - watch
    apiGroups:
      - "samplecontroller.k8s.io"
    resources:
      - foos
      - foos/status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sample-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sample-controller
subjects:
  - kind: ServiceAccount
    namespace: sample-controller
    name: sample-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-controller
  namespace: sample-controller
spec:
  selector:
    matchLabels:
      app: sample-controller
  template:
    metadata:
      labels:
        app: sample-controller
    spec:
      containers:
        - name: sample-controller
          image: gcr.io/google-samples/sample-controller:latest
          imagePullPolicy: Always
          command:
            - /sample-controller
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/kubernetes/sa
              readOnly: true
